Update patch set 1
Patch Set 1:

ugh...

This looks like a new dependency which does not appear to be in Fedora...

DEBUG:     from pylxd import api as lxd_api
DEBUG: ImportError: No module named pylxd

$ dnf provides /usr/lib/python2.7/site-packages/pylxd
Last metadata expiration check performed 23 days, 13:27:44 ago on Mon Feb  8 06:30:05 2016.
Error: No Matches found

Patch-set: 1
Label: Code-Review=0